---
deployment:
  tasks:
    - export APP=/home/bluerdcc/repositories/blue

    # Installer les dépendances (au cas où)
    - cd $APP && /usr/bin/npm install --omit=dev

    # PAS de npm run build ici : le build est déjà fait en local et commité

    # Redémarrer Passenger / l'app Node
    - /bin/mkdir -p $APP/tmp
    - /usr/bin/touch $APP/tmp/restart.txt
