---
deployment:
  tasks:
    - export REPO=/home/bluerdcc/repositories/blue
    - export APP=/home/bluerdcc/apps/blue

    # Build dans le dépôt
    - cd $REPO && /usr/bin/npm ci
    - cd $REPO && /usr/bin/npm run build

    # Publier vers le dossier d'exécution de l'app Node
    - /bin/mkdir -p $APP
    - /usr/bin/rsync -a --delete \
        --exclude=".git" \
        --exclude=".cpanel.yml" \
        $REPO/ $APP/

    # Installer en prod + redémarrer Passenger
    - cd $APP && /usr/bin/npm ci --omit=dev
    - /bin/mkdir -p $APP/tmp
    - /usr/bin/touch $APP/tmp/restart.txt
