---
deployment:
  tasks:
    - export APP=/home/bluerdcc/repositories/blue

    # Install des dépendances dans le dossier de l'app
    - cd $APP && /usr/bin/npm install

    # Build Next (standalone)
    - cd $APP && /usr/bin/npm run build

    # Redémarrer Passenger (Node app)
    - /bin/mkdir -p $APP/tmp
    - /usr/bin/touch $APP/tmp/restart.txt
