---
deployment:
  tasks:
    - export APP=/home/bluerdcc/apps/blue
    # Ici tu peux juste copier des fichiers si tu veux, mais PAS de npm run build
    - /bin/mkdir -p $APP/tmp
    - /usr/bin/touch $APP/tmp/restart.txt
